---
# === Network ===
subnet:      "192.168.109.0/24"
domain_name: "nhom07.ctk46mmt"
web_domain:  "web.nhom07.ctk46mmt"
wp_siteurl_scheme: "https"

# === Host IPs ===
dns_server_ip: "192.168.109.5"
web01_ip:      "192.168.109.11"
web02_ip:      "192.168.109.12"
nfs_server_ip: "192.168.109.13"
db_server_ip:  "192.168.109.14"
haproxy_ip:    "192.168.109.15"

# === NFS ===
nfs_share_path: "/srv/nfs/wordpress"
nfs_mount_path: "/var/www/html"

# === Database ===
db_name:          "nhom07_db"
db_user:          "nhom07"
db_password:      "123"
db_root_password: "123"

# === WordPress ===
wp_table_prefix:   "nhom07"

# === HAProxy ===
haproxy_stats_user:     "admin"
haproxy_stats_password: "123"

# === Backup ===
backup_dir:            "/opt/backup"
backup_retention_days: 7