[dns_servers]
dns-server ansible_host=192.168.109.5

[web_servers]
web01 ansible_host=192.168.109.11
web02 ansible_host=192.168.109.12

[nfs_servers]
nfs-server ansible_host=192.168.109.13

[db_servers]
mariadb-server ansible_host=192.168.109.14

[lb_servers]
haproxy ansible_host=192.168.109.15

[task7:children]
dns_servers
nfs_servers
db_servers

[task8:children]
dns_servers
nfs_servers
db_servers
lb_servers

[all:vars]
ansible_user                 = root
ansible_ssh_private_key_file = ~/.ssh/id_rsa
ansible_python_interpreter   = /usr/bin/python3
