---
- name: Install BIND9
  apt:
    name: [bind9, bind9utils, dnsutils]
    state: present
    update_cache: yes
  tags: dns

- name: Deploy named.conf.options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0644'
  notify: Restart BIND9
  tags: dns

- name: Deploy named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0644'
  notify: Restart BIND9
  tags: dns

- name: Create zones directory
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: '0755'
  tags: dns

- name: Deploy forward zone file
  template:
    src: db.zone.j2
    dest: /etc/bind/zones/db.{{ domain_name }}
    owner: root
    group: bind
    mode: '0644'
  notify: Restart BIND9
  tags: dns

- name: Allow DNS port 53
  ufw:
    rule: allow
    port: '53'
    proto: "{{ item }}"
  loop: [tcp, udp]
  tags: dns

- name: Start and enable BIND9
  service:
    name: named
    state: started
    enabled: yes
  tags: dns
